<?php
require 'class/materiaux.class.php';
require 'class/Obj.class.php';

    $materiaux = array(
        0 => new Matériaux(array('nom' => "Enseignement de la Liberté",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/liberte2.jpg')),
        1 => new Matériaux(array('nom' => "Guide de la Liberté",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/liberte3.jpg')),
        2 => new Matériaux(array('nom' => "Philosophie de la Liberté",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/liberte4.jpg')),
        3 => new Matériaux(array('nom' => "Enseignement de la Résistance",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/resistance2.jpg')),
        4 => new Matériaux(array('nom' => "Guide de la Résistance",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/resistance3.jpg')),
        5 => new Matériaux(array('nom' => "Philosophie de la Résistance",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/resistance4.jpg')),
        6 => new Matériaux(array('nom' => "Enseignement de la Poésie",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/poesie2.jpg')),
        7 => new Matériaux(array('nom' => "Guide de la Poésie",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/poesie3.jpg')),
        8 => new Matériaux(array('nom' => "Philosophie de la Poésie",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/poesie4.jpg')),
        
        9 => new Matériaux(array('nom' => "Enseignement de la Prospérité",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/prosperite2.jpg')),
        10 => new Matériaux(array('nom' => "Guide de la Prospérité",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/prosperite3.jpg')),
        11 => new Matériaux(array('nom' => "Philosophie de la Prospérité",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/prosperite4.jpg')),
        12 => new Matériaux(array('nom' => "Enseignement de la Diligence",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/diligence2.jpg')),
        13 => new Matériaux(array('nom' => "Guide de la Diligence",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/diligence3.jpg')),
        14 => new Matériaux(array('nom' => "Philosophie de la Diligence",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/diligence4.jpg')),
        15 => new Matériaux(array('nom' => "Enseignement de l'Or",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/or2.jpg')),
        16 => new Matériaux(array('nom' => "Guide de l'Or",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/or3.jpg')),
        17 => new Matériaux(array('nom' => "Philosophie de l'Or",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/or4.jpg')),

        18 => new Matériaux(array('nom' => "Enseignement de l'Éphémère",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/ephemere2.jpg')),
        19 => new Matériaux(array('nom' => "Guide de l'Éphémère",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/ephemere3.jpg')),
        20 => new Matériaux(array('nom' => "Philosophie de l'Éphémère",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/ephemere4.jpg')),
        21 => new Matériaux(array('nom' => "Enseignement de l'Élégance",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/elegance2.jpg')),
        22 => new Matériaux(array('nom' => "Guide de l'Élégance",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/elegance3.jpg')),
        23 => new Matériaux(array('nom' => "Philosophie de l'Élégance",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/elegance4.jpg')),
        24 => new Matériaux(array('nom' => "Enseignement de la Lumière",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/lumiere2.jpg')),
        25 => new Matériaux(array('nom' => "Guide de la Lumière",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/lumiere3.jpg')),
        26 => new Matériaux(array('nom' => "Philosophie de la Lumière",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/lumiere4.jpg')),

        27 => new Matériaux(array('nom' => "Enseignement de l'Admonestation",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/admonestation2.jpg')),
        28 => new Matériaux(array('nom' => "Guide de l'Admonestation",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/admonestation3.jpg')),
        29 => new Matériaux(array('nom' => "Philosophie de l'Admonestation",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/admonestation4.jpg')),
        30 => new Matériaux(array('nom' => "Enseignement de l'Ingénuité",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/ingenuite2.jpg')),
        31 => new Matériaux(array('nom' => "Guide de l'Ingénuité",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/ingenuite3.jpg')),
        32 => new Matériaux(array('nom' => "Philosophie de l'Ingénuité",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/ingenuite4.jpg')),
        33 => new Matériaux(array('nom' => "Enseignement de l'Usage",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/usage2.jpg')),
        34 => new Matériaux(array('nom' => "Guide de l'Usage",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/usage3.jpg')),
        35 => new Matériaux(array('nom' => "Philosophie de l'Usage",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/usage4.jpg')),

        36 => new Matériaux(array('nom' => "Enseignement de l'Équité",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/equite2.jpg')),
        37 => new Matériaux(array('nom' => "Guide de l'Équité",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/equite3.jpg')),
        38 => new Matériaux(array('nom' => "Philosophie de l'Équité",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/aptitude/equite4.jpg')),
        39 => new Matériaux(array('nom' => "Enseignement de la Justice",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/justice2.jpg')),
        40 => new Matériaux(array('nom' => "Guide de la Justice",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/justice3.jpg')),
        41 => new Matériaux(array('nom' => "Philosophie de la Justice",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/aptitude/justice4.jpg')),
        42 => new Matériaux(array('nom' => "Enseignement de l'Ordre",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/ordre2.jpg')),
        43 => new Matériaux(array('nom' => "Guide de l'Ordre",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/ordre3.jpg')),
        44 => new Matériaux(array('nom' => "Philosophie de l'Ordre",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/aptitude/ordre4.jpg')),

        45 => new Matériaux(array('nom' => "Tuile de la tour de Decarabian",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/tuile2.jpg')),
        46 => new Matériaux(array('nom' => "Débris de la ville de Decarabian",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/tuile3.jpg')),
        48 => new Matériaux(array('nom' => "Fragment de l'épopée de Decarabian",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/tuile4.jpg')),
        49 => new Matériaux(array('nom' => "Morceau épars du rêve de Decarabian",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/tuile5.jpg')),
        50 => new Matériaux(array('nom' => "Dent de lait du loup boréal",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/dent2.jpg')),
        51 => new Matériaux(array('nom' => "Dent cassée du loup boréal",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/dent3.jpg')),
        52 => new Matériaux(array('nom' => "Croc brisé du loup boréal",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/dent4.jpg')),
        53 => new Matériaux(array('nom' => "La nostalgie du loup boréal",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/dent5.jpg')),
        54 => new Matériaux(array('nom' => "Entraves du Chevalier du Croc de Lion",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/fers2.jpg')),
        55 => new Matériaux(array('nom' => "Chaînes du Chevalier du Croc de Lion",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/fers3.jpg')),
        56 => new Matériaux(array('nom' => "Menottes du Chevalier du Croc de Lion",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/fers4.jpg')),
        57 => new Matériaux(array('nom' => "Idéaux du Chevalier du Croc de Lion",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/fers5.jpg')),

        58 => new Matériaux(array('nom' => "Sable lumineux de Guyun",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/guyun2.jpg')),
        59 => new Matériaux(array('nom' => "Roche lustrée de Guyun",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/guyun3.jpg')),
        60 => new Matériaux(array('nom' => "Squelette sacré de Guyun",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/guyun4.jpg')),
        61 => new Matériaux(array('nom' => "Corps divin de Guyun",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/guyun5.jpg')),
        62 => new Matériaux(array('nom' => "Plomb karstique",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/karstique2.jpg')),
        63 => new Matériaux(array('nom' => "Mercure karstique",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/karstique3.jpg')),
        64 => new Matériaux(array('nom' => "Argent karstique",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/karstique4.jpg')),
        65 => new Matériaux(array('nom' => "Or karstique",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/karstique5.jpg')),
        66 => new Matériaux(array('nom' => "Grain d'aérosidérite noire",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/aerosiderite2.jpg')),
        67 => new Matériaux(array('nom' => "Éclat d'aérosidérite noire",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/aerosiderite3.jpg')),
        68 => new Matériaux(array('nom' => "Fragment d'aérosidérite noire",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/aerosiderite4.jpg')),
        69 => new Matériaux(array('nom' => "Morceau d'aérosidérite noire",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/aerosiderite5.jpg')),

        70 => new Matériaux(array('nom' => "Branche marine de corail",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/branche2.jpg')),
        71 => new Matériaux(array('nom' => "Branche marine de gemme",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/branche3.jpg')),
        72 => new Matériaux(array('nom' => "Branche marine de jade",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/branche4.jpg')),
        73 => new Matériaux(array('nom' => "Branche marine d'or",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/branche5.jpg')),
        74 => new Matériaux(array('nom' => "Sagesse de Narukami",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/narukami2.jpg')),
        75 => new Matériaux(array('nom' => "Joie de Narukami",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/narukami3.jpg')),
        76 => new Matériaux(array('nom' => "Affection de Narukami",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/narukami4.jpg')),
        77 => new Matériaux(array('nom' => "Vaillance de Narukami",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/narukami5.jpg')),
        78 => new Matériaux(array('nom' => "Masque du lieutenant pernicieux",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/masque2.jpg')),
        79 => new Matériaux(array('nom' => "Masque de la morsure du tigre",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/masque3.jpg')),
        80 => new Matériaux(array('nom' => "Masque du cornu",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/masque4.jpg')),
        81 => new Matériaux(array('nom' => "Masque du kijin",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/masque5.jpg')),

        82 => new Matériaux(array('nom' => "Talisman en cuivre de la rosée",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/talisman2.jpg')),
        83 => new Matériaux(array('nom' => "Talisman en fer de la rosée",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/talisman3.jpg')),
        84 => new Matériaux(array('nom' => "Talisman en argent de la rosée",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/talisman4.jpg')),
        85 => new Matériaux(array('nom' => "Talisman en or de la rosée",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/talisman5.jpg')),
        86 => new Matériaux(array('nom' => "Souvenir du jardin d'oasis",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/oasis2.jpg')),
        87 => new Matériaux(array('nom' => "Gentillesse du jardin d'oasis",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/oasis3.jpg')),
        88 => new Matériaux(array('nom' => "Deuil du jardin d'oasis",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/oasis4.jpg')),
        89 => new Matériaux(array('nom' => "Vérité du jardin d'oasis",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/oasis5.jpg')),
        90 => new Matériaux(array('nom' => "Dernier écho du pouvoir brûlant",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/pouvoir2.jpg')),
        91 => new Matériaux(array('nom' => "Éclat subsistant du pouvoir brûlant",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/pouvoir3.jpg')),
        92 => new Matériaux(array('nom' => "Rêve dominant du pouvoir brûlant",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/pouvoir4.jpg')),
        93 => new Matériaux(array('nom' => "Passé glorieux du pouvoir brûlant",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/pouvoir5.jpg')),

        94 => new Matériaux(array('nom' => "Fragment d'un accord ancien",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/accord2.jpg')),
        95 => new Matériaux(array('nom' => "Chapitre d'un accord ancien",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/accord3.jpg')),
        96 => new Matériaux(array('nom' => "Mouvement d'un accord ancien",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/accord4.jpg')),
        97 => new Matériaux(array('nom' => "Écho d'un accord ancien",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/arme/accord5.jpg')),
        98 => new Matériaux(array('nom' => "Résidu de rosée sacrée pure",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/rosee2.jpg')),
        99 => new Matériaux(array('nom' => "Sublimation de rosée sacrée pure",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/rosee3.jpg')),
        100 => new Matériaux(array('nom' => "Source de rosée sacrée pure",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/rosee4.jpg')),
        101 => new Matériaux(array('nom' => "Essence de rosée sacrée pure",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/arme/rosee5.jpg')),
        102 => new Matériaux(array('nom' => "Gobelet brisé de la mer immaculée",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/gobelet2.jpg')),
        103 => new Matériaux(array('nom' => "Gobelet à vin de la mer immaculée",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/gobelet3.jpg')),
        104 => new Matériaux(array('nom' => "Gobelet d'argent de la mer immaculée",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/gobelet4.jpg')),
        105 => new Matériaux(array('nom' => "Gobelet d'or de la mer immaculée",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/arme/gobelet5.jpg')),
    );

    $personnages = array(
        0 => new Objet('Amber'),
        1 => new Objet('Kaeya'),
        2 => new Objet('Lisa'),
        3 => new Objet('Barbara'),
        4 => new Objet('Razor'),
        5 => new Objet('Xiangling'),
        6 => new Objet('Beidou'),
        7 => new Objet('Xingqiu'),
        8 => new Objet('Ningguang'),
        9 => new Objet('Fischl'),
        10 => new Objet('Bennett'),
        11 => new Objet('Noelle'),
        12 => new Objet('Chongyun'),
        13 => new Objet('Sucrose'),
        14 => new Objet('Jean'),
        15 => new Objet('Diluc'),
        16 => new Objet('Qiqi'),
        17 => new Objet('Mona'),
        18 => new Objet('Keqing'),
        19 => new Objet('Venti'),
        20 => new Objet('Klee'),
        21 => new Objet('Diona'),
        22 => new Objet('Tartaglia'),
        23 => new Objet('Xinyan'),
        24 => new Objet('Zhongli'),
        25 => new Objet('Albedo'),
        26 => new Objet('Ganyu'),
        27 => new Objet('Xiao'),
        28 => new Objet('Hu Tao'),
        29 => new Objet('Rosaria'),
        30 => new Objet('Yanfei'),
        31 => new Objet('Eula'),
        32 => new Objet('Kazuha'),
        33 => new Objet('Ayaka'),
        34 => new Objet('Sayu'),
        35 => new Objet('Yoimiya'),
        36 => new Objet('Kujou Sara'),
        37 => new Objet('Raiden Shogun'),
        38 => new Objet('Kokomi'),
        39 => new Objet('Thomas'),
        40 => new Objet('Gorou'),
        41 => new Objet('Arataki Itto'),
        42 => new Objet('Yunjin'),
        43 => new Objet('Shenhe'),
        44 => new Objet('Yae Miko'),
        45 => new Objet('Ayato'),
        46 => new Objet('Yelan'),
        47 => new Objet('Kuki Shinobu'),
        48 => new Objet('Heizou'),
        49 => new Objet('Collei'),
        50 => new Objet('Tighnari'),
        51 => new Objet('Dori'),
        52 => new Objet('Candace'),
        53 => new Objet('Cyno'),
        54 => new Objet('Nilou'),
        55 => new Objet('Nahida'),
        56 => new Objet('Layla'),
        57 => new Objet('Faruzan'),
        58 => new Objet('Wanderer'),
        59 => new Objet('Yaoyao'),
        60 => new Objet('Alhaitham'),
        61 => new Objet('Dehya'),
        62 => new Objet('Mika'),
        63 => new Objet('Kaveh'),
        64 => new Objet('Baizhu'),
        65 => new Objet('Kirara'),
        66 => new Objet('Lynette'),
        67 => new Objet('Lyney'),
        68 => new Objet('Freminet'),
        69 => new Objet('Neuvillette'),
        70 => new Objet('Wriothesley'),
        71 => new Objet('Furina'),
        72 => new Objet('Charlotte')
    );

    $armes = array(
        0 => new Objet("Épée du faucon"),
        1 => new Objet("Arc d'Amos"),
        2 => new Objet("L'origine des Quatre Vents"),
        3 => new Objet("Mort-du-loup"),
        4 => new Objet("Ailes de la Voûte d'Azur"),
        5 => new Objet("Chaînes mortelles"),
        6 => new Objet("Perceur Prismatique"),
        7 => new Objet("Lame brute"),
        8 => new Objet('Tranche-Sommets'),
        9 => new Objet("Atlas de la Voûte d'Azur"),
        10 => new Objet("Fierté de la Voûte d'Azur"),
        11 => new Objet("Lance de jade ailée"),
        12 => new Objet("Coupeur de jade primordial"),
        13 => new Objet('Bâton de Homa'),
        14 => new Objet("Ultime soupir"),
        15 => new Objet("Lame de la Voûte d'Azur"),
        16 => new Objet("Ode au chant du vent"),
        17 => new Objet("Serment de la liberté"),
        18 => new Objet("Reflet de tranche-brume"),
        19 => new Objet("Berge de la Voûte d'Azur"),
        20 => new Objet("Pulsation du tonnerre"),
        21 => new Objet("Lumière du faucheur"),
        22 => new Objet("Lueur de la lune éternelle"),
        23 => new Objet("Étoile polaire"),
        24 => new Objet("Brise-pierre de corne rouge"),
        25 => new Objet("Étouffeur de calamités"),
        26 => new Objet("Vérité de Kagura"),
        27 => new Objet("Lune ondulante de Futsu"),
        28 => new Objet("Simulacre d'eau"),
        29 => new Objet("La voie du chasseur"),
        30 => new Objet("Bâton des sables écarlates"),
        31 => new Objet("Clé de Khaj-Nisut"),
        32 => new Objet("Mille rêves flottants"),
        33 => new Objet("Mémoire de Tulaytullah"),
        34 => new Objet("Lumière d'incision foliaire"),
        35 => new Objet("Balise de la mer de roseaux"),
        36 => new Objet("Splendeur de l’azur"),
        37 => new Objet("La première grande magie"),
        38 => new Objet("Tome du flux éternel")
    );

    $artefacts = array(
        0 => new Objet("Rideau du Gladiateur"),
        1 => new Objet("Bande Vagabonde"),
        2 => new Objet("Ancien rituel royal"),
        3 => new Objet("Chevalerie ensanglantée"),
        4 => new Objet("Amour chéri"),
        5 => new Objet("Ombre de la Verte Chasseuse"),
        6 => new Objet("Roche ancienne"),
        7 => new Objet("Météore inversé"),
        8 => new Objet("Dompteur de foudre"),
        9 => new Objet("Colère de tonnerre"),
        10 => new Objet("Marcheur du feu"),
        11 => new Objet("Sorcière des flammes ardentes"),
        12 => new Objet("Briseur de glace"),
        13 => new Objet("Âme des profondeurs"),
        14 => new Objet("Ténacité du Millelithe"),
        15 => new Objet("Flamme blême"),
        16 => new Objet("Réminiscence nostalgique"),
        17 => new Objet("Emblème du destin brisé"),
        18 => new Objet("Coquille des rêves opulents"),
        19 => new Objet("Palourde aux teintes océaniques"),
        20 => new Objet("Au-delà cinabrin"),
        21 => new Objet("Échos d'une offrande"),
        22 => new Objet("Souvenir de forêt"),
        23 => new Objet("Rêve doré"),
        24 => new Objet("Chronique du Pavillon du désert"),
        25 => new Objet("Fleur du paradis perdu"),
        26 => new Objet("Rêve de la nymphe"),
        27 => new Objet("Lueur du vourukasha"),
        28 => new Objet("Chasseur de la Maréchaussée"),
        29 => new Objet("Troupe dorée")
    );
?>