<?php
require 'class/arme.class.php';
require 'class/materiaux.class.php';
require 'class/perso.class.php';

    $materiaux = array(
        0 => new Matériaux(array('nom' => "Enseignement de la Liberté",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/liberte2.jpg')),
        1 => new Matériaux(array('nom' => "Guide de la Liberté",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/liberte3.jpg')),
        2 => new Matériaux(array('nom' => "Philosophie de la Liberté",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/liberte4.jpg')),
        3 => new Matériaux(array('nom' => "Enseignement de la Résistance",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/resistance2.jpg')),
        4 => new Matériaux(array('nom' => "Guide de la Résistance",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/resistance3.jpg')),
        5 => new Matériaux(array('nom' => "Philosophie de la Résistance",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/resistance4.jpg')),
        6 => new Matériaux(array('nom' => "Enseignement de la Poésie",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/poesie2.jpg')),
        7 => new Matériaux(array('nom' => "Guide de la Poésie",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/poesie3.jpg')),
        8 => new Matériaux(array('nom' => "Philosophie de la Poésie",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/poesie4.jpg')),
        
        9 => new Matériaux(array('nom' => "Enseignement de la Prospérité",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/prosperite2.jpg')),
        10 => new Matériaux(array('nom' => "Guide de la Prospérité",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/prosperite3.jpg')),
        11 => new Matériaux(array('nom' => "Philosophie de la Prospérité",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/prosperite4.jpg')),
        12 => new Matériaux(array('nom' => "Enseignement de la Diligence",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/diligence2.jpg')),
        13 => new Matériaux(array('nom' => "Guide de la Diligence",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/diligence3.jpg')),
        14 => new Matériaux(array('nom' => "Philosophie de la Diligence",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/diligence4.jpg')),
        15 => new Matériaux(array('nom' => "Enseignement de l'Or",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/or2.jpg')),
        16 => new Matériaux(array('nom' => "Guide de l'Or",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/or3.jpg')),
        17 => new Matériaux(array('nom' => "Philosophie de l'Or",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/or4.jpg')),

        18 => new Matériaux(array('nom' => "Enseignement de l'Éphémère",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/ephemere2.jpg')),
        19 => new Matériaux(array('nom' => "Guide de l'Éphémère",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/ephemere3.jpg')),
        20 => new Matériaux(array('nom' => "Philosophie de l'Éphémère",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/ephemere4.jpg')),
        21 => new Matériaux(array('nom' => "Enseignement de l'Élégance",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/elegance2.jpg')),
        22 => new Matériaux(array('nom' => "Guide de l'Élégance",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/elegance3.jpg')),
        23 => new Matériaux(array('nom' => "Philosophie de l'Élégance",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/elegance4.jpg')),
        24 => new Matériaux(array('nom' => "Enseignement de la Lumière",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/lumiere2.jpg')),
        25 => new Matériaux(array('nom' => "Guide de la Lumière",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/lumiere3.jpg')),
        26 => new Matériaux(array('nom' => "Philosophie de la Lumière",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/lumiere4.jpg')),

        27 => new Matériaux(array('nom' => "Enseignement de l'Admonestation",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/admonestation2.jpg')),
        28 => new Matériaux(array('nom' => "Guide de l'Admonestation",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/admonestation3.jpg')),
        29 => new Matériaux(array('nom' => "Philosophie de l'Admonestation",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/admonestation4.jpg')),
        30 => new Matériaux(array('nom' => "Enseignement de l'Ingénuité",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/ingenuite2.jpg')),
        31 => new Matériaux(array('nom' => "Guide de l'Ingénuité",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/ingenuite3.jpg')),
        32 => new Matériaux(array('nom' => "Philosophie de l'Ingénuité",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/ingenuite4.jpg')),
        33 => new Matériaux(array('nom' => "Enseignement de l'Usage",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/usage2.jpg')),
        34 => new Matériaux(array('nom' => "Guide de l'Usage",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/usage3.jpg')),
        35 => new Matériaux(array('nom' => "Philosophie de l'Usage",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/usage4.jpg')),

        36 => new Matériaux(array('nom' => "Enseignement de l'Équité",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/equite2.jpg')),
        37 => new Matériaux(array('nom' => "Guide de l'Équité",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/equite3.jpg')),
        38 => new Matériaux(array('nom' => "Philosophie de l'Équité",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/equite4.jpg')),
        39 => new Matériaux(array('nom' => "Enseignement de la Justice",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/justice2.jpg')),
        40 => new Matériaux(array('nom' => "Guide de la Justice",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/justice3.jpg')),
        41 => new Matériaux(array('nom' => "Philosophie de la Justice",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/justice4.jpg')),
        42 => new Matériaux(array('nom' => "Enseignement de l'Ordre",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/ordre2.jpg')),
        43 => new Matériaux(array('nom' => "Guide de l'Ordre",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/ordre3.jpg')),
        44 => new Matériaux(array('nom' => "Philosophie de l'Ordre",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/ordre4.jpg')),

        45 => new Matériaux(array('nom' => "Tuile de la tour de Decarabian",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile2.jpg')),
        46 => new Matériaux(array('nom' => "Débris de la ville de Decarabian",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile3.jpg')),
        48 => new Matériaux(array('nom' => "Fragment de l'épopée de Decarabian",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile4.jpg')),
        49 => new Matériaux(array('nom' => "Morceau épars du rêve de Decarabian",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile5.jpg')),
        50 => new Matériaux(array('nom' => "Dent de lait du loup boréal",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent2.jpg')),
        51 => new Matériaux(array('nom' => "Dent cassée du loup boréal",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent3.jpg')),
        52 => new Matériaux(array('nom' => "Croc brisé du loup boréal",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent4.jpg')),
        53 => new Matériaux(array('nom' => "La nostalgie du loup boréal",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent5.jpg')),
        54 => new Matériaux(array('nom' => "Entraves du Chevalier du Croc de Lion",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers2.jpg')),
        55 => new Matériaux(array('nom' => "Chaînes du Chevalier du Croc de Lion",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers3.jpg')),
        56 => new Matériaux(array('nom' => "Menottes du Chevalier du Croc de Lion",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers4.jpg')),
        57 => new Matériaux(array('nom' => "Idéaux du Chevalier du Croc de Lion",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers5.jpg')),

        58 => new Matériaux(array('nom' => "Sable lumineux de Guyun",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun2.jpg')),
        59 => new Matériaux(array('nom' => "Roche lustrée de Guyun",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun3.jpg')),
        60 => new Matériaux(array('nom' => "Squelette sacré de Guyun",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun4.jpg')),
        61 => new Matériaux(array('nom' => "Corps divin de Guyun",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun5.jpg')),
        62 => new Matériaux(array('nom' => "Plomb karstique",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique2.jpg')),
        63 => new Matériaux(array('nom' => "Mercure karstique",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique3.jpg')),
        64 => new Matériaux(array('nom' => "Argent karstique",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique4.jpg')),
        65 => new Matériaux(array('nom' => "Or karstique",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique5.jpg')),
        66 => new Matériaux(array('nom' => "Grain d'aérosidérite noire",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite2.jpg')),
        67 => new Matériaux(array('nom' => "Éclat d'aérosidérite noire",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite3.jpg')),
        68 => new Matériaux(array('nom' => "Fragment d'aérosidérite noire",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite4.jpg')),
        69 => new Matériaux(array('nom' => "Morceau d'aérosidérite noire",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite5.jpg')),

        70 => new Matériaux(array('nom' => "Branche marine de corail",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche2.jpg')),
        71 => new Matériaux(array('nom' => "Branche marine de gemme",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche3.jpg')),
        72 => new Matériaux(array('nom' => "Branche marine de jade",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche4.jpg')),
        73 => new Matériaux(array('nom' => "Branche marine d'or",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche5.jpg')),
        74 => new Matériaux(array('nom' => "Sagesse de Narukami",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami2.jpg')),
        75 => new Matériaux(array('nom' => "Joie de Narukami",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami3.jpg')),
        76 => new Matériaux(array('nom' => "Affection de Narukami",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami4.jpg')),
        77 => new Matériaux(array('nom' => "Vaillance de Narukami",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami5.jpg')),
        78 => new Matériaux(array('nom' => "Masque du lieutenant pernicieux",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque2.jpg')),
        79 => new Matériaux(array('nom' => "Masque de la morsure du tigre",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque3.jpg')),
        80 => new Matériaux(array('nom' => "Masque du cornu",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque4.jpg')),
        81 => new Matériaux(array('nom' => "Masque du kijin",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque5.jpg')),

        82 => new Matériaux(array('nom' => "Talisman en cuivre de la rosée",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman2.jpg')),
        83 => new Matériaux(array('nom' => "Talisman en fer de la rosée",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman3.jpg')),
        84 => new Matériaux(array('nom' => "Talisman en argent de la rosée",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman4.jpg')),
        85 => new Matériaux(array('nom' => "Talisman en or de la rosée",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman5.jpg')),
        86 => new Matériaux(array('nom' => "Souvenir du jardin d'oasis",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis2.jpg')),
        87 => new Matériaux(array('nom' => "Gentillesse du jardin d'oasis",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis3.jpg')),
        88 => new Matériaux(array('nom' => "Deuil du jardin d'oasis",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis4.jpg')),
        89 => new Matériaux(array('nom' => "Vérité du jardin d'oasis",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis5.jpg')),
        90 => new Matériaux(array('nom' => "Dernier écho du pouvoir brûlant",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir2.jpg')),
        91 => new Matériaux(array('nom' => "Éclat subsistant du pouvoir brûlant",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir3.jpg')),
        92 => new Matériaux(array('nom' => "Rêve dominant du pouvoir brûlant",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir4.jpg')),
        93 => new Matériaux(array('nom' => "Passé glorieux du pouvoir brûlant",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir5.jpg')),

        94 => new Matériaux(array('nom' => "Fragment d'un accord ancien",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord2.jpg')),
        95 => new Matériaux(array('nom' => "Chapitre d'un accord ancien",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord3.jpg')),
        96 => new Matériaux(array('nom' => "Mouvement d'un accord ancien",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord4.jpg')),
        97 => new Matériaux(array('nom' => "Écho d'un accord ancien",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord5.jpg')),
        98 => new Matériaux(array('nom' => "Résidu de rosée sacrée pure",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee2.jpg')),
        99 => new Matériaux(array('nom' => "Sublimation de rosée sacrée pure",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee3.jpg')),
        100 => new Matériaux(array('nom' => "Source de rosée sacrée pure",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee4.jpg')),
        101 => new Matériaux(array('nom' => "Essence de rosée sacrée pure",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee5.jpg')),
        102 => new Matériaux(array('nom' => "Gobelet brisé de la mer immaculée",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet2.jpg')),
        103 => new Matériaux(array('nom' => "Gobelet à vin de la mer immaculée",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet3.jpg')),
        104 => new Matériaux(array('nom' => "Gobelet d'argent de la mer immaculée",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet4.jpg')),
        105 => new Matériaux(array('nom' => "Gobelet d'or de la mer immaculée",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet5.jpg')),
    );

    $personnages = array(
        0 => new Personnage('Amber'),
        1 => new Personnage('Kaeya'),
        2 => new Personnage('Lisa'),
        3 => new Personnage('Barbara'),
        4 => new Personnage('Razor'),
        5 => new Personnage('Xiangling'),
        6 => new Personnage('Beidou'),
        7 => new Personnage('Xingqiu'),
        8 => new Personnage('Ningguang'),
        9 => new Personnage('Fischl'),
        10 => new Personnage('Bennett'),
        11 => new Personnage('Noelle'),
        12 => new Personnage('Chongyun'),
        13 => new Personnage('Sucrose'),
        14 => new Personnage('Jean'),
        15 => new Personnage('Diluc'),
        16 => new Personnage('Qiqi'),
        17 => new Personnage('Mona'),
        18 => new Personnage('Keqing'),
        19 => new Personnage('Venti'),
        20 => new Personnage('Klee'),
        21 => new Personnage('Diona'),
        22 => new Personnage('Tartaglia'),
        23 => new Personnage('Xinyan'),
        24 => new Personnage('Zhongli'),
        25 => new Personnage('Albedo'),
        26 => new Personnage('Ganyu'),
        27 => new Personnage('Xiao'),
        28 => new Personnage('Hu Tao'),
        29 => new Personnage('Rosaria'),
        30 => new Personnage('Yanfei'),
        31 => new Personnage('Eula'),
        32 => new Personnage('Kazuha'),
        33 => new Personnage('Ayaka'),
        34 => new Personnage('Sayu'),
        35 => new Personnage('Yoimiya'),
        36 => new Personnage('Kujou Sara'),
        37 => new Personnage('Raiden Shogun'),
        38 => new Personnage('Kokomi'),
        39 => new Personnage('Thomas'),
        40 => new Personnage('Gorou'),
        41 => new Personnage('Arataki Itto'),
        42 => new Personnage('Yunjin'),
        43 => new Personnage('Shenhe'),
        44 => new Personnage('Yae Miko'),
        45 => new Personnage('Ayato'),
        46 => new Personnage('Yelan'),
        47 => new Personnage('Kuki Shinobu'),
        48 => new Personnage('Heizou'),
        49 => new Personnage('Collei'),
        50 => new Personnage('Tighnari'),
        51 => new Personnage('Dori'),
        52 => new Personnage('Candace'),
        53 => new Personnage('Cyno'),
        54 => new Personnage('Nilou'),
        55 => new Personnage('Nahida'),
        56 => new Personnage('Layla'),
        57 => new Personnage('Faruzan'),
        58 => new Personnage('Wanderer'),
        59 => new Personnage('Yaoyao'),
        60 => new Personnage('Alhaitham'),
        61 => new Personnage('Dehya'),
        62 => new Personnage('Mika'),
        63 => new Personnage('Kaveh'),
        64 => new Personnage('Baizhu'),
        65 => new Personnage('Kirara'),
        66 => new Personnage('Lynette'),
        67 => new Personnage('Lyney'),
        68 => new Personnage('Freminet'),
        69 => new Personnage('Neuvillette'),
        70 => new Personnage('Wriothesley'),
        71 => new Personnage('Furina'),
        72 => new Personnage('Charlotte')
    );

    $armes = array(
        0 => new Arme("Épée du faucon", 5),
        1 => new Arme("Arc d'Amos", 5),
        2 => new Arme("L'origine des Quatre Vents", 5),
        3 => new Arme("Mort-du-loup", 5),
        4 => new Arme("Ailes de la Voûte d'Azur", 5),
        5 => new Arme("Chaînes mortelles", 5),
        6 => new Arme("Perceur Prismatique", 5),
        7 => new Arme("Lame brute", 5),
        8 => new Arme('Tranche-Sommets', 5),
        9 => new Arme("Atlas de la Voûte d'Azur", 5),
        10 => new Arme("Fierté de la Voûte d'Azur", 5),
        11 => new Arme("Lance de jade ailée", 5),
        12 => new Arme("Coupeur de jade primordial", 5),
        13 => new Arme('Bâton de Homa', 5),
        14 => new Arme("Ultime soupir", 5),
        15 => new Arme("Lame de la Voûte d'Azur", 5),
        16 => new Arme("Ode au chant du vent", 5),
        17 => new Arme("Serment de la liberté", 5),
        18 => new Arme("Reflet de tranche-brume", 5),
        19 => new Arme("Berge de la Voûte d'Azur", 5),
        20 => new Arme("Pulsation du tonnerre", 5),
        21 => new Arme("Lumière du faucheur", 5),
        22 => new Arme("Lueur de la lune éternelle", 5),
        23 => new Arme("Étoile polaire", 5),
        24 => new Arme("Brise-pierre de corne rouge", 5),
        25 => new Arme("Étouffeur de calamités", 5),
        26 => new Arme("Vérité de Kagura", 5),
        27 => new Arme("Lune ondulante de Futsu", 5),
        28 => new Arme("Simulacre d'eau", 5),
        29 => new Arme("La voie du chasseur", 5),
        30 => new Arme("Bâton des sables écarlates", 5),
        31 => new Arme("Clé de Khaj-Nisut", 5),
        32 => new Arme("Mille rêves flottants", 5),
        33 => new Arme("Mémoire de Tulaytullah", 5),
        34 => new Arme("Lumière d'incision foliaire", 5),
        35 => new Arme("Balise de la mer de roseaux", 5),
        36 => new Arme("Splendeur de l’azur", 5),
        37 => new Arme("La première grande magie", 5),
        38 => new Arme("Tome du flux éternel", 5),
    );
?>