<?php
require 'class/arme.class.php';
require 'class/materiaux.class.php';
require 'class/perso.class.php';

    $materiaux = array(
        0 => new Matériaux(array('nom' => "Enseignement de la Liberté",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/liberte2.jpg')),
        1 => new Matériaux(array('nom' => "Guide de la Liberté",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/liberte3.jpg')),
        2 => new Matériaux(array('nom' => "Philosophie de la Liberté",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/liberte4.jpg')),
        3 => new Matériaux(array('nom' => "Enseignement de la Résistance",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/resistance2.jpg')),
        4 => new Matériaux(array('nom' => "Guide de la Résistance",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/resistance3.jpg')),
        5 => new Matériaux(array('nom' => "Philosophie de la Résistance",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/resistance4.jpg')),
        6 => new Matériaux(array('nom' => "Enseignement de la Poésie",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/poesie2.jpg')),
        7 => new Matériaux(array('nom' => "Guide de la Poésie",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/poesie3.jpg')),
        8 => new Matériaux(array('nom' => "Philosophie de la Poésie",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/poesie4.jpg')),
        
        9 => new Matériaux(array('nom' => "Enseignement de la Prospérité",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/prosperite2.jpg')),
        10 => new Matériaux(array('nom' => "Guide de la Prospérité",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/prosperite3.jpg')),
        11 => new Matériaux(array('nom' => "Philosophie de la Prospérité",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/prosperite4.jpg')),
        12 => new Matériaux(array('nom' => "Enseignement de la Diligence",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/diligence2.jpg')),
        13 => new Matériaux(array('nom' => "Guide de la Diligence",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/diligence3.jpg')),
        14 => new Matériaux(array('nom' => "Philosophie de la Diligence",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/diligence4.jpg')),
        15 => new Matériaux(array('nom' => "Enseignement de l'Or",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/or2.jpg')),
        16 => new Matériaux(array('nom' => "Guide de l'Or",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/or3.jpg')),
        17 => new Matériaux(array('nom' => "Philosophie de l'Or",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/or4.jpg')),

        18 => new Matériaux(array('nom' => "Enseignement de l'Éphémère",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/ephemere2.jpg')),
        19 => new Matériaux(array('nom' => "Guide de l'Éphémère",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/ephemere3.jpg')),
        20 => new Matériaux(array('nom' => "Philosophie de l'Éphémère",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/ephemere4.jpg')),
        21 => new Matériaux(array('nom' => "Enseignement de l'Élégance",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/elegance2.jpg')),
        22 => new Matériaux(array('nom' => "Guide de l'Élégance",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/elegance3.jpg')),
        23 => new Matériaux(array('nom' => "Philosophie de l'Élégance",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/elegance4.jpg')),
        24 => new Matériaux(array('nom' => "Enseignement de la Lumière",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/lumiere2.jpg')),
        25 => new Matériaux(array('nom' => "Guide de la Lumière",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/lumiere3.jpg')),
        26 => new Matériaux(array('nom' => "Philosophie de la Lumière",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/lumiere4.jpg')),

        27 => new Matériaux(array('nom' => "Enseignement de l'Admonestation",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/admonestation2.jpg')),
        28 => new Matériaux(array('nom' => "Guide de l'Admonestation",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/admonestation3.jpg')),
        29 => new Matériaux(array('nom' => "Philosophie de l'Admonestation",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/admonestation4.jpg')),
        30 => new Matériaux(array('nom' => "Enseignement de l'Ingénuité",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/ingenuite2.jpg')),
        31 => new Matériaux(array('nom' => "Guide de l'Ingénuité",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/ingenuite3.jpg')),
        32 => new Matériaux(array('nom' => "Philosophie de l'Ingénuité",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/ingenuite4.jpg')),
        33 => new Matériaux(array('nom' => "Enseignement de l'Usage",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/usage2.jpg')),
        34 => new Matériaux(array('nom' => "Guide de l'Usage",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/usage3.jpg')),
        35 => new Matériaux(array('nom' => "Philosophie de l'Usage",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/usage4.jpg')),

        36 => new Matériaux(array('nom' => "Enseignement de l'Équité",'star'=>2,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/equite2.jpg')),
        37 => new Matériaux(array('nom' => "Guide de l'Équité",'star'=>3,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/equite3.jpg')),
        38 => new Matériaux(array('nom' => "Philosophie de l'Équité",'star'=>4,'type'=>'aptitude','jour' => 1,'img'=>'img/materiaux/equite4.jpg')),
        39 => new Matériaux(array('nom' => "Enseignement de la Justice",'star'=>2,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/justice2.jpg')),
        40 => new Matériaux(array('nom' => "Guide de la Justice",'star'=>3,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/justice3.jpg')),
        41 => new Matériaux(array('nom' => "Philosophie de la Justice",'star'=>4,'type'=>'aptitude','jour' => 2,'img'=>'img/materiaux/justice4.jpg')),
        42 => new Matériaux(array('nom' => "Enseignement de l'Ordre",'star'=>2,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/ordre2.jpg')),
        43 => new Matériaux(array('nom' => "Guide de l'Ordre",'star'=>3,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/ordre3.jpg')),
        44 => new Matériaux(array('nom' => "Philosophie de l'Ordre",'star'=>4,'type'=>'aptitude','jour' => 3,'img'=>'img/materiaux/ordre4.jpg')),

        45 => new Matériaux(array('nom' => "Tuile de la tour de Decarabian",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile2.jpg')),
        46 => new Matériaux(array('nom' => "Débris de la ville de Decarabian",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile3.jpg')),
        48 => new Matériaux(array('nom' => "Fragment de l'épopée de Decarabian",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile4.jpg')),
        49 => new Matériaux(array('nom' => "Morceau épars du rêve de Decarabian",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/tuile5.jpg')),
        50 => new Matériaux(array('nom' => "Dent de lait du loup boréal",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent2.jpg')),
        51 => new Matériaux(array('nom' => "Dent cassée du loup boréal",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent3.jpg')),
        52 => new Matériaux(array('nom' => "Croc brisé du loup boréal",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent4.jpg')),
        53 => new Matériaux(array('nom' => "La nostalgie du loup boréal",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/dent5.jpg')),
        54 => new Matériaux(array('nom' => "Entraves du Chevalier du Croc de Lion",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers2.jpg')),
        55 => new Matériaux(array('nom' => "Chaînes du Chevalier du Croc de Lion",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers3.jpg')),
        56 => new Matériaux(array('nom' => "Menottes du Chevalier du Croc de Lion",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers4.jpg')),
        57 => new Matériaux(array('nom' => "Idéaux du Chevalier du Croc de Lion",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/fers5.jpg')),

        58 => new Matériaux(array('nom' => "Sable lumineux de Guyun",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun2.jpg')),
        59 => new Matériaux(array('nom' => "Roche lustrée de Guyun",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun3.jpg')),
        60 => new Matériaux(array('nom' => "Squelette sacré de Guyun",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun4.jpg')),
        61 => new Matériaux(array('nom' => "Corps divin de Guyun",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/guyun5.jpg')),
        62 => new Matériaux(array('nom' => "Plomb karstique",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique2.jpg')),
        63 => new Matériaux(array('nom' => "Mercure karstique",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique3.jpg')),
        64 => new Matériaux(array('nom' => "Argent karstique",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique4.jpg')),
        65 => new Matériaux(array('nom' => "Or karstique",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/karstique5.jpg')),
        66 => new Matériaux(array('nom' => "Grain d'aérosidérite noire",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite2.jpg')),
        67 => new Matériaux(array('nom' => "Éclat d'aérosidérite noire",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite3.jpg')),
        68 => new Matériaux(array('nom' => "Fragment d'aérosidérite noire",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite4.jpg')),
        69 => new Matériaux(array('nom' => "Morceau d'aérosidérite noire",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/aerosiderite5.jpg')),

        70 => new Matériaux(array('nom' => "Branche marine de corail",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche2.jpg')),
        71 => new Matériaux(array('nom' => "Branche marine de gemme",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche3.jpg')),
        72 => new Matériaux(array('nom' => "Branche marine de jade",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche4.jpg')),
        73 => new Matériaux(array('nom' => "Branche marine d'or",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/branche5.jpg')),
        74 => new Matériaux(array('nom' => "Sagesse de Narukami",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami2.jpg')),
        75 => new Matériaux(array('nom' => "Joie de Narukami",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami3.jpg')),
        76 => new Matériaux(array('nom' => "Affection de Narukami",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami4.jpg')),
        77 => new Matériaux(array('nom' => "Vaillance de Narukami",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/narukami5.jpg')),
        78 => new Matériaux(array('nom' => "Masque du lieutenant pernicieux",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque2.jpg')),
        79 => new Matériaux(array('nom' => "Masque de la morsure du tigre",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque3.jpg')),
        80 => new Matériaux(array('nom' => "Masque du cornu",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque4.jpg')),
        81 => new Matériaux(array('nom' => "Masque du kijin",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/masque5.jpg')),

        82 => new Matériaux(array('nom' => "Talisman en cuivre de la rosée",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman2.jpg')),
        83 => new Matériaux(array('nom' => "Talisman en fer de la rosée",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman3.jpg')),
        84 => new Matériaux(array('nom' => "Talisman en argent de la rosée",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman4.jpg')),
        85 => new Matériaux(array('nom' => "Talisman en or de la rosée",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/talisman5.jpg')),
        86 => new Matériaux(array('nom' => "Souvenir du jardin d'oasis",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis2.jpg')),
        87 => new Matériaux(array('nom' => "Gentillesse du jardin d'oasis",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis3.jpg')),
        88 => new Matériaux(array('nom' => "Deuil du jardin d'oasis",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis4.jpg')),
        89 => new Matériaux(array('nom' => "Vérité du jardin d'oasis",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/oasis5.jpg')),
        90 => new Matériaux(array('nom' => "Dernier écho du pouvoir brûlant",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir2.jpg')),
        91 => new Matériaux(array('nom' => "Éclat subsistant du pouvoir brûlant",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir3.jpg')),
        92 => new Matériaux(array('nom' => "Rêve dominant du pouvoir brûlant",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir4.jpg')),
        93 => new Matériaux(array('nom' => "Passé glorieux du pouvoir brûlant",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/pouvoir5.jpg')),

        94 => new Matériaux(array('nom' => "Fragment d'un accord ancien",'star'=>2,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord2.jpg')),
        95 => new Matériaux(array('nom' => "Chapitre d'un accord ancien",'star'=>3,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord3.jpg')),
        96 => new Matériaux(array('nom' => "Mouvement d'un accord ancien",'star'=>4,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord4.jpg')),
        97 => new Matériaux(array('nom' => "Écho d'un accord ancien",'star'=>5,'type'=>'arme','jour' => 1,'img'=>'img/materiaux/accord5.jpg')),
        98 => new Matériaux(array('nom' => "Résidu de rosée sacrée pure",'star'=>2,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee2.jpg')),
        99 => new Matériaux(array('nom' => "Sublimation de rosée sacrée pure",'star'=>3,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee3.jpg')),
        100 => new Matériaux(array('nom' => "Source de rosée sacrée pure",'star'=>4,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee4.jpg')),
        101 => new Matériaux(array('nom' => "Essence de rosée sacrée pure",'star'=>5,'type'=>'arme','jour' => 2,'img'=>'img/materiaux/rosee5.jpg')),
        102 => new Matériaux(array('nom' => "Gobelet brisé de la mer immaculée",'star'=>2,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet2.jpg')),
        103 => new Matériaux(array('nom' => "Gobelet à vin de la mer immaculée",'star'=>3,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet3.jpg')),
        104 => new Matériaux(array('nom' => "Gobelet d'argent de la mer immaculée",'star'=>4,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet4.jpg')),
        105 => new Matériaux(array('nom' => "Gobelet d'or de la mer immaculée",'star'=>5,'type'=>'arme','jour' => 3,'img'=>'img/materiaux/gobelet5.jpg')),
    );

    $personnages = array(
        0 => new Personnage(array('img'=>'Furina_Card','lien'=>'Furina')),
        1 => new Personnage(array('img'=>'Albedo_Card','lien'=>'Albedo')),
        2 => new Personnage(array('img'=>'Alhaitham_Card','lien'=>'Alhaitham')),
        3 => new Personnage(array('img'=>'Amber_Card','lien'=>'Amber')),
        4 => new Personnage(array('img'=>'Ayaka_Card','lien'=>'Ayaka')),
        5 => new Personnage(array('img'=>'Ayato_Card','lien'=>'Ayato')),
        6 => new Personnage(array('img'=>'Baizhu_Card','lien'=>'Baizhu')),
        7 => new Personnage(array('img'=>'Barbara_Card','lien'=>'Barbara')),
        8 => new Personnage(array('img'=>'Beidou_Card','lien'=>'Beidou')),
        9 => new Personnage(array('img'=>'Bennett_Card','lien'=>'Bennett')),
        10 => new Personnage(array('img'=>'Candace_Card','lien'=>'Candace')),
        11 => new Personnage(array('img'=>'Chongyun_Card','lien'=>'Chongyun')),
        12 => new Personnage(array('img'=>'Collei_Card','lien'=>'Collei')),
        13 => new Personnage(array('img'=>'Cyno_Card','lien'=>'Cyno')),
        14 => new Personnage(array('img'=>'Dehya_Card','lien'=>'Dehya')),
        15 => new Personnage(array('img'=>'Diluc_Card','lien'=>'Diluc')),
        16 => new Personnage(array('img'=>'Diona_Card','lien'=>'Diona')),
        17 => new Personnage(array('img'=>'Dori_Card','lien'=>'Dori')),
        18 => new Personnage(array('img'=>'Ei_Card','lien'=>'Ei')),
        19 => new Personnage(array('img'=>'Eula_Card','lien'=>'Eula')),
        20 => new Personnage(array('img'=>'Faruzan_Card','lien'=>'Faruzan')),
        21 => new Personnage(array('img'=>'Fischl_Card','lien'=>'Fischl')),
        22 => new Personnage(array('img'=>'Freminet_Card','lien'=>'Freminet')),
        23 => new Personnage(array('img'=>'Ganyu_Card','lien'=>'Ganyu')),
        24 => new Personnage(array('img'=>'Gorou_Card','lien'=>'Gorou')),
        25 => new Personnage(array('img'=>'Heizou_Card','lien'=>'Heizou')),
        26 => new Personnage(array('img'=>'Hu_Card','lien'=>'Hu')),
        27 => new Personnage(array('img'=>'Itto_Card','lien'=>'Itto')),
        28 => new Personnage(array('img'=>'Jean_Card','lien'=>'Jean')),
        29 => new Personnage(array('img'=>'Kaeya_Card','lien'=>'Kaeya')),
        30 => new Personnage(array('img'=>'Kaveh_Card','lien'=>'Kaveh')),
        31 => new Personnage(array('img'=>'Kazuha_Card','lien'=>'Kazuha')),
        32 => new Personnage(array('img'=>'Keqing_Card','lien'=>'Keqing')),
        33 => new Personnage(array('img'=>'Kirara_Card','lien'=>'Kirara')),
        34 => new Personnage(array('img'=>'Klee_Card','lien'=>'Klee')),
        35 => new Personnage(array('img'=>'Kokomi_Card','lien'=>'Kokomi')),
        36 => new Personnage(array('img'=>'Kuki_Card','lien'=>'Kuki')),
        37 => new Personnage(array('img'=>'Layla_Card','lien'=>'Layla')),
        38 => new Personnage(array('img'=>'Lisa_Card','lien'=>'Lisa')),
        39 => new Personnage(array('img'=>'Lynette_Card','lien'=>'Lynette')),
        40 => new Personnage(array('img'=>'Lyney_Card','lien'=>'Lyney')),
        41 => new Personnage(array('img'=>'Mika_Card','lien'=>'Mika')),
        42 => new Personnage(array('img'=>'Miko_Card','lien'=>'Miko')),
        43 => new Personnage(array('img'=>'Mona_Card','lien'=>'Mona')),
        44 => new Personnage(array('img'=>'Nahida_Card','lien'=>'Nahida')),
        45 => new Personnage(array('img'=>'Nilou_Card','lien'=>'Nilou')),
        46 => new Personnage(array('img'=>'Ningguang_Card','lien'=>'Ningguang')),
        47 => new Personnage(array('img'=>'Noelle_Card','lien'=>'Noellle')),
        48 => new Personnage(array('img'=>'Qiqi_Card','lien'=>'Qiqi')),
        49 => new Personnage(array('img'=>'Razor_Card','lien'=>'Razor')),
        50 => new Personnage(array('img'=>'Rosaria_Card','lien'=>'Rosaria')),
        51 => new Personnage(array('img'=>'Sara_Card','lien'=>'Sara')),
        52 => new Personnage(array('img'=>'Sayu_Card','lien'=>'Sayu')),
        53 => new Personnage(array('img'=>'Shenhe_Card','lien'=>'Shenhe')),
        54 => new Personnage(array('img'=>'Sucrose_Card','lien'=>'Sucrose')),
        55 => new Personnage(array('img'=>'Tartaglia_Card','lien'=>'Tartaglia')),
        56 => new Personnage(array('img'=>'Thomas_Card','lien'=>'Thomas')),
        57 => new Personnage(array('img'=>'Xiangling_Card','lien'=>'Xiangling')),
        58 => new Personnage(array('img'=>'Xiao_Card','lien'=>'Xiao')),
        59 => new Personnage(array('img'=>'Xingqiu_Card','lien'=>'Xingqiu')),
        60 => new Personnage(array('img'=>'Xinyan_Card','lien'=>'Xinyan')),
        61 => new Personnage(array('img'=>'Yanfei_Card','lien'=>'Yanfei')),
        62 => new Personnage(array('img'=>'Yaoyao_Card','lien'=>'Yaoyao')),
        63 => new Personnage(array('img'=>'Yelan_Card','lien'=>'Yelan')),
        64 => new Personnage(array('img'=>'Yoimiya_Card','lien'=>'Yoimiya')),
        65 => new Personnage(array('img'=>'Yun_Card','lien'=>'Yun')),
        66 => new Personnage(array('img'=>'Zhongli_Card','lien'=>'Zhongli'))
    );
?>